### ISSUE TITLE
💡 "Fire and Forget" Execution of Sidecar Lambdas

### ISSUE THREAD

**Issue by jryd** [hammerstonedev/sidecar#35]
We have a use case for Sidecar where we want to "fire and forget", where our function needs to do some work, but we don't care about the result.

As such, we don't want to be waiting around for the result.

The issue with the existing asynchronous functionality is that you still need to wait for the requests to settle, otherwise the function won't be invoked.

From some initial diving, the AWS SDK is using Guzzle under-the-hood and so this is probably a limitation of Guzzle more than it is this package or the SDK itself.

I think there's a valid use case here, where people have lambda function's that perform "background tasks" or "processing". These functions don't return anything but perform a set of actions and as such you don't want to hold up execution of your application whilst these run.
Some examples that spring to mind:
* image processing
* fetching meta data
* audio/image/video optimisation

For our specific use case, we have an event that takes place in our system and we want to dispatch a sidecar function. 
The sidecar function polls an API looking for a particular flag. 
When that flag is present, it runs a new API call and then exits.

We've had this running as a queued job in our application, but when our queue is occasionally congested, the job doesn't run immediately on the queue.
We run on Vapor and given how the queues work, we cannot setup a separate queue that is invoked immediately or is given a higher priority.
The job we want to run is time-sensitive and so needs to run ASAP. 
We use Sidecar for a couple things already and thought this could be a solution as we could asynchronously execute the Sidecar function and then continue on and have this run immediately in the background.

From some initial thinking, this would probably be best strung up with SNS and SQS whereby we notify a topic and then subscribe and invoke the Sidecar function.
We're happy to look at drafting a PR that would add this functionality, but before doing so, we wanted to see if this was something that you'd consider adding to Sidecar, and if so, whether there is a different approach that you might take.

**Comment by rhysemmerson** [comment]
Reading the docs this may be possible to do using EVENT as the invocation type.

https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax

**Comment by rhysemmerson** [comment]
> 
> Honestly this is news to me, and definitely not ideal. I guess all my async invocations have been fast enough that they settle before the response terminates. Thanks for bringing this to my attention.
> 

It was surprising to me as well, apparently it's a limitation of guzzle's async implementation https://github.com/guzzle/guzzle/issues/1429#issue-140477252

Having the fire and forget method would be preferable in our situation because the lambda can take a few seconds to run and blocking the worker while the lambda runs will impact our http capacity.

To add to that the app in question is running on vapor with the fpm runtime which calls terminate before sending the response so waiting on the sidecar would block the http response.

**Comment by aarondfrancis** [comment]
Boom, merged! I'll update the notes and release it here in a bit. Thanks yall!

**Comment by sentiasa** [comment]
The executeAsEvent() implementation is very useful - thanks a lot!

I have a similar case but for running many fire-and-forget functions. Would it be possible to achieve something like `executeManyAsEvent()` so that if I have to run 20 lambda functions (as fire and forget), it'd do them all at once.

Otherwise, one option would be using https://github.com/spatie/async.

What do you think?

**Comment by rhysemmerson** [comment]
@sentiasa I think this will do what you want. The first call to `settled()` will trigger all the requests to be sent.

```PHP

collect([
  Sidecar::execute($function, $payload, $async = true, $invocationType = 'Event'),
  Sidecar::execute($function, $payload2, $async = true, $invocationType = 'Event'),
  // ...
])->map->settled();


```
