### ISSUE TITLE
[Question/Bug] Function Warming does not appear to be working

### ISSUE THREAD

**Issue by roberttolton** [hammerstonedev/sidecar#95]
Hi, thanks for the work on this package.

I have a function deployed and it's working great. However, the warming does not appear to work.

It has a warmingConfig of:

```
return new WarmingConfig(2);
```

I have the warming command in my schedule, like so:
```
$schedule->command('sidecar:warm')->everyFiveMinutes();
```

I have also manually run the warm command, and also run the helper through `tinker`. No errors.

However, I can't see any requests coming through to my function for warming. If I trigger the function myself with a real payload, I see the request, it works fine. But obviously the first request is much longer because of a cold-start (12s versus 3s), hence the desire for warming.

Re-reading the documentation, I don't believe I have missed anything, but I also cannot find or raise any errors or exceptions from the warming function, so I'm not sure which stage is failing.

Any ideas?

**Comment by ttrushin** [comment]
@roberttolton I believe it has to do with this: https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeAsync.html

Looks like InvokeAsync was deprecated at some point.

The `execute` method in the Sidecar `Manager` class is doing this:
```php
$method = $async ? 'invokeAsync' : 'invoke';

// ...

$result = app(LambdaClient::class)->{$method}([ // ...
```

when it should be doing this:

```php
$result = app(LambdaClient::class)->invoke([ // ...
```

I fixed this issue in my fork and have had success with warming. 

Good luck!

**Comment by aarondfrancis** [comment]
Sorry about that! Just fixed it. 

So the issue was actually different than what @ttrushin was saying, but his fix would have actually worked.

`invokeAsync` is deprecated as an API call, but not as a method in the AWS SDK library. `invokeAsync` in the SDK just relies on Guzzle to use it's multi-curl handler to run multiple requests at once. Not truly async. 

In the `warm` command we were getting a bunch of requests ready to be sent out, but never actually sending them. Oops. This wasn't an issue with `prewarming`, but was with warming. Should be all fixed now!
